In [1008]:
# Import all the libraries
import pandas as pd
import glob
import os
import re
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
from pprint import pprint

In [1009]:
#Get all CSV files in the folder of GA
all_files = glob.glob(r"C:\Huy Phan\College\VoterTurnout\data\WI\*.csv")

# Files that contain both 'precinct' and 'general' in the filename
general_files = [
    f for f in all_files
    if all(word in f.lower() for word in ['general'])
]

# Files that contain both 'precinct' and 'primary' in the filename
primary_files = [
    f for f in all_files
    if all(word in f.lower() for word in ['primary'])
]

In [1010]:
print("General files:")
for f in general_files:
    print(f)

General files:
C:\Huy Phan\College\VoterTurnout\data\WI\20160405__wi__general__ward.csv
C:\Huy Phan\College\VoterTurnout\data\WI\20161108__wi__general__ward.csv

In [1011]:
print("\nPrimary files:")
for f in primary_files:
    print(f)

Primary files:
C:\Huy Phan\College\VoterTurnout\data\WI\20160216__wi__primary__ward.csv
C:\Huy Phan\College\VoterTurnout\data\WI\20160405__wi__primary__ward.csv
C:\Huy Phan\College\VoterTurnout\data\WI\20160809__wi__primary__ward.csv

In [1012]:
# Process primary files
primary_df_list = []

for file in primary_files:
    try:
        df = pd.read_csv(file)
        # Filtering out only President 
        if 'office' in df.columns:
            df = df[df["office"] == "President"]
            
        # Combine precinct as county + precinct
        df["precinct"] = df["county"].astype(str) + df["ward"].astype(str)
        df["precinct"] = df["precinct"].str.upper()

        # Cleaning maybe total precinct
        if 'precinct' in df.columns:
            df['precinct'] = df['precinct'].astype(str)                  
            df = df[df['precinct'].str.upper() != "TOTAL"]               
            df = df[df['precinct'].str.strip().str.upper() != "TOTAL"]   
            df = df[df['precinct'].str.upper() != "NAN"]                
            df = df[~df['precinct'].str.upper().str.contains(r"\w*TOTAL\w*", na=False)]   

        if 'county' in df.columns:
            df['county'] = df['county'].astype(str)                  
            df = df[df['county'].str.upper() != "TOTAL"]               
            df = df[df['county'].str.strip().str.upper() != "TOTAL"]   
            df = df[df['county'].str.upper() != "NAN"]       
            df = df[~df['county'].str.upper().str.contains(r"\w*TOTAL\w*", na=False)]               
        
        # Dropping duplicates value
        df = df.drop_duplicates()
        primary_df_list.append(df)

    except Exception as e:
        print(f"Error in {file}: {e}")

# Combine all cleaned files
pri_combined_df = pd.concat(primary_df_list, ignore_index=True)
pri_combined_df

,county,ward,office,district,total votes,party,candidate,votes,precinct
0,Adams,Town Of Adams Wards 1-3,President,NaN,271,REP,Marco Rubio,3,ADAMSTOWN OF ADAMS WARDS 1-3
1,Adams,Town Of Adams Wards 1-3,President,NaN,271,REP,Ben Carson,0,ADAMSTOWN OF ADAMS WARDS 1-3
2,Adams,Town Of Adams Wards 1-3,President,NaN,271,REP,Rand Paul,2,ADAMSTOWN OF ADAMS WARDS 1-3
3,Adams,Town Of Adams Wards 1-3,President,NaN,271,REP,Mike Huckabee,1,ADAMSTOWN OF ADAMS WARDS 1-3
4,Adams,Town Of Adams Wards 1-3,President,NaN,271,REP,Jim Gilmore,0,ADAMSTOWN OF ADAMS WARDS 1-3
...,...,...,...,...,...,...,...,...,...
81475,Wood,"City Of Wisconsin Rapids Wards 16-23,25",President,NaN,775,DEM,Martin O'Malley,3,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25"
81476,Wood,"City Of Wisconsin Rapids Wards 16-23,25",President,NaN,775,DEM,Bernie Sanders,388,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25"
81477,Wood,"City Of Wisconsin Rapids Wards 16-23,25",President,NaN,775,DEM,Uninstructed Delegation,1,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25"
81478,Wood,"City Of Wisconsin Rapids Wards 16-23,25",President,NaN,775,DEM,Roque Rocky De La Fuente (Write-In),0,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25"
81479,Wood,"City Of Wisconsin Rapids Wards 16-23,25",President,NaN,775,DEM,Scattering,0,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25"

In [1013]:
#Load the filtered data
pri_filtered_out = pd.read_csv("WI_primary_filtered.csv")
gen_filtered_out = pd.read_csv("WI_general_filtered.csv")

# Get unique precinct names from primary_filtered_out and general_filtered_out
primary_precincts = pri_filtered_out["precinct"].dropna().unique()
general_precincts = gen_filtered_out["precinct"].dropna().unique()

# Create a mapping dictionary for precinct replacements
precinct_map = {}

# Loop through precincts in pri_filtered_out and find closest match in general_filtered_out
for p1 in primary_precincts:
    match, score = process.extractOne(p1, general_precincts, scorer=fuzz.token_sort_ratio)
    if score >= 90:  # Adjust threshold if needed
            precinct_map[p1] = match

In [1014]:
# List of precincts to remove
# Fix for WAUPACACITY OF CLINTONVILLE WARD 2 to WARD 5
pri_combined_df.loc[
    (
        pri_combined_df["precinct"].str.contains("WAUPACACITY OF CLINTONVILLE WARD 2", case=False, na=False) |
        pri_combined_df["precinct"].str.contains("WAUPACACITY OF CLINTONVILLE WARD 3", case=False, na=False) |
        pri_combined_df["precinct"].str.contains("WAUPACACITY OF CLINTONVILLE WARD 4", case=False, na=False) |
        pri_combined_df["precinct"].str.contains("WAUPACACITY OF CLINTONVILLE WARD 5", case=False, na=False)
    ),
    "precinct"
] = "WAUPACACITY OF CLINTONVILLE WARD 1-7"

# Fix for BAYFIELDCITY OF WASHBURN WARD 1 to WARD 4
pri_combined_df.loc[
    (
        pri_combined_df["precinct"].str.contains("BAYFIELDCITY OF WASHBURN WARD 1", case=False, na=False) |
        pri_combined_df["precinct"].str.contains("BAYFIELDCITY OF WASHBURN WARD 2", case=False, na=False) |
        pri_combined_df["precinct"].str.contains("BAYFIELDCITY OF WASHBURN WARD 3", case=False, na=False) |
        pri_combined_df["precinct"].str.contains("BAYFIELDCITY OF WASHBURN WARD 4", case=False, na=False)
    ),
    "precinct"
] = "BAYFIELDCITY OF WASHBURN WARD 1-4"

# Fix for BAYFIELDTOWN OF EILEEN WARD 1 and 2
pri_combined_df.loc[
    (
        pri_combined_df["precinct"].str.contains("BAYFIELDTOWN OF EILEEN WARD 1", case=False, na=False) |
        pri_combined_df["precinct"].str.contains("BAYFIELDTOWN OF EILEEN WARD 2", case=False, na=False)
    ),
    "precinct"
] = "BAYFIELDTOWN OF EILEEN WARD 1-2"

precincts_to_remove = [
    "BARRONVILLAGE OF NEW AUBURN WARDS 2-3",
    "BROWNCITY OF DE PERE WARD 13",
    "BROWNCITY OF DE PERE WARDS 1-2,4",
    "BROWNCITY OF DE PERE WARDS 14-15",
    "BROWNCITY OF DE PERE WARDS 3-5",
    "BROWNTOWN OF NEW DENMARK WARD 3",
    "BROWNVILLAGE OF HOBART WARD 1-5",
    "BROWNVILLAGE OF HOBART WARD 6-9",
    "BROWNVILLAGE OF HOWARD WARD 13",
    "BROWNVILLAGE OF HOWARD WARD 14",
    "BROWNVILLAGE OF HOWARD WARD 15",
    "BROWNVILLAGE OF HOWARD WARD 16",   
    "BROWNVILLAGE OF HOWARD WARD 18",
    "BROWNVILLAGE OF HOWARD WARD 3-4",
    "BROWNVILLAGE OF HOWARD WARD 5-6",
    "BROWNVILLAGE OF HOWARD WARD 7-8",
    "DANECITY OF FITCHBURG WARD 1-4",
    "COLUMBIACITY OF WISCONSIN DELLS WARDS 1-3,6,11",
    "DANECITY OF STOUGHTON WARD 7-9",
    "DANETOWN OF CROSS PLAINS WARD 1-3",
    "DANETOWN OF VERONA WARD 1-4",
    "DANEVILLAGE OF BROOKLYN WARDS 1,3",
    "DANEVILLAGE OF DEFOREST WARD 7-13",
    "DANEVILLAGE OF WINDSOR WARDS 1-10",
    "DODGETOWN OF LOWELL WARD 1-4",
    "DODGETOWN OF WESTFORD WARD 1-2,4",
    "FOND DU LACTOWN OF CALUMET WARDS 1-2",
    "FOND DU LACTOWN OF ROSENDALE WARD 2",
    "GREENTOWN OF MOUNT PLEASANT WARD 3",
    "GREENTOWN OF MOUNT PLEASANT WARDS 1-2",
    "GREENVILLAGE OF HORTONVILLE WARD 3",
    "JEFFERSONCITY OF FORT ATKINSON WARDS 1-2",
    "JEFFERSONCITY OF FORT ATKINSON WARDS 7,9",
    "JEFFERSONCITY OF JEFFERSON WARD 10",
    "JEFFERSONCITY OF JEFFERSON WARD 5",
    "JEFFERSONCITY OF JEFFERSON WARDS 1-2",
    "JEFFERSONCITY OF WATERTOWN WARDS 8,19",
    "KENOSHATOWN OF SOMERS WARDS 1-2",
    "LA CROSSETOWN OF SHELBY WARDS 1-6",
    "MANITOWOCCITY OF MANITOWOC WARD 17-18",
    "MANITOWOCCITY OF MANITOWOC WARD 19-20",
    "MANITOWOCCITY OF MANITOWOC WARD 21-24",
    "MANITOWOCCITY OF MANITOWOC WARD 3-4",
    "MARATHONCITY OF ABBOTSFORD WARDS 1,6",
    "MONROETOWN OF LA GRANGE WARDS 2A-3A",
    "MONROETOWN OF LA GRANGE WARDS 2B-3B",
    "OCONTOCITY OF OCONTO FALLS WARD 1-6",
    "OUTAGAMIETOWN OF GRAND CHUTE WARDS 5-7",
    "OUTAGAMIETOWN OF GRAND CHUTE WARDS 8-10",
    "OUTAGAMIETOWN OF GREENVILLE WARDS 1-5",
    "OUTAGAMIETOWN OF GREENVILLE WARDS 6,9",
    "OUTAGAMIETOWN OF GREENVILLE WARDS 7-8",
    "OUTAGAMIEVILLAGE OF LITTLE CHUTE WARDS 1,3,9-11,14",
    "OUTAGAMIEVILLAGE OF LITTLE CHUTE WARDS 2,13",
    "OUTAGAMIEVILLAGE OF LITTLE CHUTE WARDS 7-8",
    "OUTAGAMIEVILLAGE OF WRIGHTSTOWN WARDS 4-5",
    "OZAUKEECITY OF MEQUON WARDS 1-2",
    "PORTAGECITY OF STEVENS POINT WARDS 28-29",
    "PORTAGECITY OF STEVENS POINT WARDS 31,33,42",
    "PORTAGECITY OF STEVENS POINT WARDS 32,34",
    "PORTAGETOWN OF HULL WARDS 4-7",
    "RACINETOWN OF BURLINGTON WARDS 8-11",
    "RACINEVILLAGE OF CALEDONIA WARDS 6-8,20",
    "RACINEVILLAGE OF MOUNT PLEASANT WARDS 5-8",
    "RICHLANDTOWN OF BUENA VISTA WARD 2",
    "ROCKTOWN OF BELOIT WARDS 7-11",
    "ROCKTOWN OF HARMONY WARDS 2-6",
    "SAUKCITY OF WISCONSIN DELLS WARDS 4,8,10",
    "ST. CROIXCITY OF NEW RICHMOND WARDS 11-12",
    "ST. CROIXCITY OF NEW RICHMOND WARDS 7-8",
    "ST. CROIXCITY OF NEW RICHMOND WARDS 9-10",
    "ST. CROIXTOWN OF RICHMOND WARD 1-5",
    "WALWORTHCITY OF ELKHORN WARD 2",
    "WALWORTHCITY OF ELKHORN WARD 3",   
    "WALWORTHCITY OF ELKHORN WARD 4,8",
    "WALWORTHCITY OF ELKHORN WARD 6",
    "WALWORTHCITY OF WHITEWATER WARDS 7-9",
    "WALWORTHTOWN OF EAST TROY WARDS 1-6",
    "WASHINGTONCITY OF HARTFORD WARDS 1-5",
    "WASHINGTONCITY OF WEST BEND WARDS 11-14,28-29",
    "WASHINGTONCITY OF WEST BEND WARDS 9-10,30-32",
    "OUTAGAMIEVILLAGE OF COMBINED LOCKS WARDS 1-4",
    "WAUKESHATOWN OF BROOKFIELD WARD 1",
    "WAUKESHATOWN OF LISBON WARD 1",
    "WAUKESHATOWN OF LISBON WARD 6",    
    "WAUKESHATOWN OF LISBON WARD 2-3",
    "WAUKESHATOWN OF MUKWONAGO WARDS 1,4-8",
    "PORTAGECITY OF STEVENS POINT WARDS 14-15",
    "PORTAGECITY OF STEVENS POINT WARDS 25-26",
    "RACINEVILLAGE OF MOUNT PLEASANT WARDS 5-8",
    "WALWORTHCITY OF DELAVAN WARDS 11-14",
    "WALWORTHCITY OF LAKE GENEVA WARDS 5-6,10",

    
    ]

# Loop through the list and remove each key from precinct_map
for precinct in precincts_to_remove:
    if precinct in precinct_map:  # Check if the precinct exists in the map
        del precinct_map[precinct]  # Remove the key-value pair

pri_combined_df["precinct"] = pri_combined_df["precinct"].replace(precinct_map)

In [1015]:
precinct_map

{'ADAMSCITY OF ADAMS WARD 1': 'ADAMSCITY OF ADAMS WARD 1-4',
 'ADAMSCITY OF ADAMS WARD 2': 'ADAMSCITY OF ADAMS WARD 1-4',
 'ADAMSCITY OF ADAMS WARD 3': 'ADAMSCITY OF ADAMS WARD 1-4',
 'ADAMSCITY OF ADAMS WARD 4': 'ADAMSCITY OF ADAMS WARD 1-4',
 'ADAMSTOWN OF EASTON WARD 1-2': 'ADAMSTOWN OF EASTON WARDS 1-2',
 'ADAMSTOWN OF ROME WARDS 1-5': 'ADAMSTOWN OF ROME WARD 1-5',
 'ASHLANDTOWN OF GORDON WARD 1': 'ASHLANDTOWN OF GORDON WARDS 1-2',
 'ASHLANDTOWN OF GORDON WARD 2': 'ASHLANDTOWN OF GORDON WARDS 1-2',
 'ASHLANDTOWN OF MARENGO WARD 1': 'ASHLANDTOWN OF MARENGO WARDS 1-2',
 'ASHLANDTOWN OF MARENGO WARD 2': 'ASHLANDTOWN OF MARENGO WARDS 1-2',
 'ASHLANDTOWN OF MORSE WARD 1': 'ASHLANDTOWN OF MORSE WARDS 1-3',
 'ASHLANDTOWN OF MORSE WARD 2': 'ASHLANDTOWN OF MORSE WARDS 1-3',
 'ASHLANDTOWN OF MORSE WARD 3': 'ASHLANDTOWN OF MORSE WARDS 1-3',
 'ASHLANDTOWN OF PEEKSVILLE WARD 1': 'ASHLANDTOWN OF PEEKSVILLE WARDS 1-2',
 'ASHLANDTOWN OF PEEKSVILLE WARD 2': 'ASHLANDTOWN OF PEEKSVILLE WARDS 1-2',
 'ASHLANDTOWN OF SANBORN WARD 1': 'ASHLANDTOWN OF SANBORN WARDS 1-2',
 'ASHLANDTOWN OF SANBORN WARD 2': 'ASHLANDTOWN OF SANBORN WARDS 1-2',
 'ASHLANDTOWN OF WHITE RIVER WARD 1': 'ASHLANDTOWN OF WHITE RIVER WARDS 1-2',
 'ASHLANDTOWN OF WHITE RIVER WARD 2': 'ASHLANDTOWN OF WHITE RIVER WARDS 1-2',
 'ASHLANDVILLAGE OF BUTTERNUT WARD 1': 'ASHLANDVILLAGE OF BUTTERNUT WARDS 1-2',
 'ASHLANDVILLAGE OF BUTTERNUT WARD 2': 'ASHLANDVILLAGE OF BUTTERNUT WARDS 1-2',
 'BARRONTOWN OF CHETEK WARD 1-2': 'BARRONTOWN OF CHETEK WARDS 1-2',
 'BAYFIELDCITY OF BAYFIELD WARDS 1-4': 'BAYFIELDCITY OF BAYFIELD WARD 1-4',
 'BAYFIELDCITY OF WASHBURN WARD 1': 'BAYFIELDCITY OF WASHBURN WARD 1-4',
 'BAYFIELDCITY OF WASHBURN WARD 2': 'BAYFIELDCITY OF WASHBURN WARD 1-4',
 'BAYFIELDCITY OF WASHBURN WARD 3': 'BAYFIELDCITY OF WASHBURN WARD 1-4',
 'BAYFIELDCITY OF WASHBURN WARD 4': 'BAYFIELDCITY OF WASHBURN WARD 1-4',
 'BAYFIELDTOWN OF EILEEN WARD 1': 'BAYFIELDTOWN OF EILEEN WARD 1-2',
 'BAYFIELDTOWN OF EILEEN WARD 2': 'BAYFIELDTOWN OF EILEEN WARD 1-2',
 'BROWNCITY OF DE PERE WARD 16': 'BROWNCITY OF DE PERE WARD 5',
 'BROWNCITY OF DE PERE WARD 17': 'BROWNCITY OF DE PERE WARD 5',
 'BROWNCITY OF DE PERE WARD 18': 'BROWNCITY OF DE PERE WARD 5',
 'BROWNCITY OF DE PERE WARD 9': 'BROWNCITY OF DE PERE WARD 5',
 'BROWNCITY OF DE PERE WARDS 3,5': 'BROWNCITY OF DE PERE WARDS 13-15',
 'BROWNTOWN OF EATON WARD 1-2': 'BROWNTOWN OF EATON WARDS 1-2',
 'BROWNTOWN OF GLENMORE WARD 1': 'BROWNTOWN OF GLENMORE WARDS 1-2',
 'BROWNTOWN OF GLENMORE WARD 2': 'BROWNTOWN OF GLENMORE WARDS 1-2',
 'BROWNTOWN OF GREEN BAY WARD 1-3': 'BROWNTOWN OF GREEN BAY WARDS 1-3',
 'BROWNTOWN OF HOLLAND WARD 1-2': 'BROWNTOWN OF HOLLAND WARDS 1-2',
 'BROWNTOWN OF HUMBOLDT WARD 1-2': 'BROWNTOWN OF HUMBOLDT WARDS 1-2',
 'BROWNTOWN OF LAWRENCE WARD 1-3': 'BROWNTOWN OF LAWRENCE WARDS 1-3',
 'BROWNTOWN OF LAWRENCE WARD 4-6': 'BROWNTOWN OF LAWRENCE WARDS 4-6',
 'BROWNTOWN OF LEDGEVIEW WARD 1': 'BROWNTOWN OF LEDGEVIEW WARDS 4-7',
 'BROWNTOWN OF LEDGEVIEW WARDS 2-10': 'BROWNTOWN OF LEDGEVIEW WARDS 4-7',
 'BROWNTOWN OF MORRISON WARD 1-2': 'BROWNTOWN OF MORRISON WARDS 1-2',
 'BROWNTOWN OF NEW DENMARK WARD 1-2': 'BROWNTOWN OF NEW DENMARK WARDS 1-3',
 'BROWNTOWN OF PITTSFIELD WARD 1-3': 'BROWNTOWN OF PITTSFIELD WARDS 1-3',
 'BROWNTOWN OF ROCKLAND WARD 1': 'BROWNTOWN OF ROCKLAND WARDS 1-3',
 'BROWNTOWN OF ROCKLAND WARD 2-3': 'BROWNTOWN OF ROCKLAND WARDS 1-3',
 'BROWNTOWN OF WRIGHTSTOWN WARD 1': 'BROWNTOWN OF WRIGHTSTOWN WARDS 1-3',
 'BROWNTOWN OF WRIGHTSTOWN WARD 2-3': 'BROWNTOWN OF WRIGHTSTOWN WARDS 1-3',
 'BROWNVILLAGE OF ALLOUEZ WARD 3': 'BROWNVILLAGE OF ALLOUEZ WARD 3-4',
 'BROWNVILLAGE OF ALLOUEZ WARD 4': 'BROWNVILLAGE OF ALLOUEZ WARD 3-4',
 'BROWNVILLAGE OF ASHWAUBENON WARD 7': 'BROWNVILLAGE OF ASHWAUBENON WARDS 7-8',
 'BROWNVILLAGE OF ASHWAUBENON WARD 8': 'BROWNVILLAGE OF ASHWAUBENON WARDS 7-8',
 'BROWNVILLAGE OF BELLEVUE WARDS 1-4': 'BROWNVILLAGE OF BELLEVUE WARDS 1-6',
 'BROWNVILLAGE OF BELLEVUE WARDS 5-6': 'BROWNVILLAGE OF BELLEVUE WARDS 1-6',
 'BROWNVILLAGE OF DENMARK WARD 1-3': 'BROWNVILLAGE OF DENMARK WARDS 1-3',
 'BROWNVILLAGE OF HOWARD WARD 1-2': 'BROWNVILLAGE OF HOWARD WARDS 1,12',
 'BROWNVILLAGE OF HOWARD WARD 11-12': 'BROWNVILLAGE OF HOWARD WARDS 1,12',
 'BROWNVILLAGE OF HOWARD WARD 9-10': 'BROWNVILLAGE OF HOWARD WARDS 9-10,18',
 'BROWNVILLAGE OF PULASKI WARD 1-3,6': 'BROWNVILLAGE OF PULASKI WARDS 1-3,6',
 'BROWNVILLAGE OF SUAMICO WARD 5': 'BROWNVILLAGE OF SUAMICO WARD 5-8',
 'BROWNVILLAGE OF SUAMICO WARD 6-8': 'BROWNVILLAGE OF SUAMICO WARD 5-8',
 'BUFFALOCITY OF MONDOVI WARD 1-3': 'BUFFALOCITY OF MONDOVI WARDS 1-3',
 'CALUMETCITY OF BRILLION WARD 1': 'CALUMETCITY OF BRILLION WARD 1-4',
 'CALUMETCITY OF BRILLION WARDS 2-4': 'CALUMETCITY OF BRILLION WARD 1-4',
 'CALUMETCITY OF CHILTON WARD 1': 'CALUMETCITY OF CHILTON WARD 1-5',
 'CALUMETCITY OF CHILTON WARD 3': 'CALUMETCITY OF CHILTON WARD 1-5',
 'CALUMETCITY OF CHILTON WARD 4': 'CALUMETCITY OF CHILTON WARD 1-5',
 'CALUMETCITY OF CHILTON WARDS 2,5': 'CALUMETCITY OF CHILTON WARD 1-5',
 'CALUMETCITY OF NEW HOLSTEIN WARD 3': 'CALUMETCITY OF NEW HOLSTEIN WARDS 1-5',
 'CALUMETCITY OF NEW HOLSTEIN WARD 4': 'CALUMETCITY OF NEW HOLSTEIN WARDS 1-5',
 'CALUMETCITY OF NEW HOLSTEIN WARD 5': 'CALUMETCITY OF NEW HOLSTEIN WARDS 1-5',
 'CALUMETCITY OF NEW HOLSTEIN WARDS 1-2': 'CALUMETCITY OF NEW HOLSTEIN WARDS 1-5',
 'CALUMETTOWN OF CHILTON WARD 1': 'CALUMETTOWN OF CHILTON WARDS 1-3',
 'CALUMETTOWN OF CHILTON WARD 2': 'CALUMETTOWN OF CHILTON WARDS 1-3',
 'CALUMETTOWN OF CHILTON WARD 3': 'CALUMETTOWN OF CHILTON WARDS 1-3',
 'CALUMETTOWN OF HARRISON WARDS 7-8': 'CALUMETTOWN OF HARRISON WARDS 7-8,10-12',
 'CALUMETTOWN OF NEW HOLSTEIN WARD 2': 'CALUMETTOWN OF NEW HOLSTEIN WARDS 1-3',
 'CALUMETTOWN OF NEW HOLSTEIN WARDS 1,3': 'CALUMETTOWN OF NEW HOLSTEIN WARDS 1-3',
 'CALUMETTOWN OF STOCKBRIDGE WARD 3': 'CALUMETTOWN OF STOCKBRIDGE WARDS 1-3',
 'CALUMETTOWN OF STOCKBRIDGE WARDS 1-2': 'CALUMETTOWN OF STOCKBRIDGE WARDS 1-3',
 'CALUMETVILLAGE OF SHERWOOD WARD 1': 'CALUMETVILLAGE OF SHERWOOD WARDS 1-5',
 'CALUMETVILLAGE OF SHERWOOD WARD 5': 'CALUMETVILLAGE OF SHERWOOD WARDS 1-5',
 'CALUMETVILLAGE OF SHERWOOD WARDS 2-4': 'CALUMETVILLAGE OF SHERWOOD WARDS 1-5',
 'CHIPPEWATOWN OF BLOOMER WARD 1-2': 'CHIPPEWATOWN OF BLOOMER WARDS 1-2',
 'CHIPPEWATOWN OF EAGLE POINT WARD 1-5': 'CHIPPEWATOWN OF EAGLE POINT WARDS 1-5',
 'CHIPPEWATOWN OF EDSON WARD 1-2': 'CHIPPEWATOWN OF EDSON WARDS 1-2',
 'CHIPPEWATOWN OF GOETZ WARD 1-2': 'CHIPPEWATOWN OF GOETZ WARDS 1-2',
 'CHIPPEWATOWN OF LAKE HOLCOMBE WARD 1-2': 'CHIPPEWATOWN OF LAKE HOLCOMBE WARDS 1-2',
 'CHIPPEWATOWN OF SIGEL WARD 1-2': 'CHIPPEWATOWN OF SIGEL WARDS 1-2',
 'CHIPPEWATOWN OF TILDEN WARD 1-3': 'CHIPPEWATOWN OF TILDEN WARDS 1-3',
 'CHIPPEWATOWN OF WHEATON WARD 1-3': 'CHIPPEWATOWN OF WHEATON WARDS 1-3',
 'CHIPPEWAVILLAGE OF CADOTT WARD 1-3': 'CHIPPEWAVILLAGE OF CADOTT WARDS 1-3',
 'CLARKCITY OF ABBOTSFORD WARD 2': 'CLARKCITY OF ABBOTSFORD WARDS 2-5',
 'CLARKCITY OF ABBOTSFORD WARD 3': 'CLARKCITY OF ABBOTSFORD WARDS 2-5',
 'CLARKCITY OF ABBOTSFORD WARD 4': 'CLARKCITY OF ABBOTSFORD WARDS 2-5',
 'CLARKCITY OF ABBOTSFORD WARD 5': 'CLARKCITY OF ABBOTSFORD WARDS 2-5',
 'CLARKCITY OF COLBY WARD 2': 'CLARKCITY OF COLBY WARDS 2-4',
 'CLARKCITY OF COLBY WARD 3': 'CLARKCITY OF COLBY WARDS 2-4',
 'CLARKCITY OF COLBY WARD 4': 'CLARKCITY OF COLBY WARDS 2-4',
 'CLARKCITY OF GREENWOOD WARD 1': 'CLARKCITY OF GREENWOOD WARDS 1-2',
 'CLARKCITY OF GREENWOOD WARD 2': 'CLARKCITY OF GREENWOOD WARDS 1-2',
 'CLARKCITY OF LOYAL WARD 1': 'CLARKCITY OF LOYAL WARDS 1-2',
 'CLARKCITY OF LOYAL WARD 2': 'CLARKCITY OF LOYAL WARDS 1-2',
 'CLARKCITY OF OWEN WARD 1': 'CLARKCITY OF OWEN WARDS 1-3',
 'CLARKCITY OF OWEN WARD 2': 'CLARKCITY OF OWEN WARDS 1-3',
 'CLARKCITY OF OWEN WARD 3': 'CLARKCITY OF OWEN WARDS 1-3',
 'CLARKCITY OF THORP WARD 1': 'CLARKCITY OF THORP WARDS 1-4',
 'CLARKCITY OF THORP WARD 2': 'CLARKCITY OF THORP WARDS 1-4',
 'CLARKCITY OF THORP WARD 3': 'CLARKCITY OF THORP WARDS 1-4',
 'CLARKCITY OF THORP WARD 4': 'CLARKCITY OF THORP WARDS 1-4',
 'CLARKTOWN OF COLBY WARD 1': 'CLARKTOWN OF COLBY WARDS 1-3',
 'CLARKTOWN OF COLBY WARD 2': 'CLARKTOWN OF COLBY WARDS 1-3',
 'CLARKTOWN OF COLBY WARD 3': 'CLARKTOWN OF COLBY WARDS 1-3',
 'CLARKTOWN OF EATON WARD 1': 'CLARKTOWN OF EATON WARDS 1-2',
 'CLARKTOWN OF EATON WARD 2': 'CLARKTOWN OF EATON WARDS 1-2',
 'CLARKTOWN OF FREMONT WARD 1': 'CLARKTOWN OF FREMONT WARDS 1-2',
 'CLARKTOWN OF FREMONT WARD 2': 'CLARKTOWN OF FREMONT WARDS 1-2',
 'CLARKTOWN OF GRANT WARD 1': 'CLARKTOWN OF GRANT WARDS 1-2',
 'CLARKTOWN OF GRANT WARD 2': 'CLARKTOWN OF GRANT WARDS 1-2',
 'CLARKTOWN OF GREEN GROVE WARD 1': 'CLARKTOWN OF GREEN GROVE WARDS 1-2',
 'CLARKTOWN OF GREEN GROVE WARD 2': 'CLARKTOWN OF GREEN GROVE WARDS 1-2',
 'CLARKTOWN OF HEWETT WARD 1': 'CLARKTOWN OF HEWETT WARDS 1-2',
 'CLARKTOWN OF HEWETT WARD 2': 'CLARKTOWN OF HEWETT WARDS 1-2',
 'CLARKTOWN OF HIXON WARD 1': 'CLARKTOWN OF HIXON WARDS 1-2',
 'CLARKTOWN OF HIXON WARD 2': 'CLARKTOWN OF HIXON WARDS 1-2',
 'CLARKTOWN OF HOARD WARD 1': 'CLARKTOWN OF HOARD WARDS 1-2',
 'CLARKTOWN OF HOARD WARD 2': 'CLARKTOWN OF HOARD WARDS 1-2',
 'CLARKTOWN OF LEVIS WARD 1': 'CLARKTOWN OF LEVIS WARDS 1-2',
 'CLARKTOWN OF LEVIS WARD 2': 'CLARKTOWN OF LEVIS WARDS 1-2',
 'CLARKTOWN OF LONGWOOD WARD 1': 'CLARKTOWN OF LONGWOOD WARDS 1-2',
 'CLARKTOWN OF LONGWOOD WARD 2': 'CLARKTOWN OF LONGWOOD WARDS 1-2',
 'CLARKTOWN OF LOYAL WARD 1': 'CLARKTOWN OF LOYAL WARDS 1-2',
 'CLARKTOWN OF LOYAL WARD 2': 'CLARKTOWN OF LOYAL WARDS 1-2',
 'CLARKTOWN OF LYNN WARD 1': 'CLARKTOWN OF LYNN WARDS 1-2',
 'CLARKTOWN OF LYNN WARD 2': 'CLARKTOWN OF LYNN WARDS 1-2',
 'CLARKTOWN OF MAYVILLE WARD 1': 'CLARKTOWN OF MAYVILLE WARDS 1-2',
 'CLARKTOWN OF MAYVILLE WARD 2': 'CLARKTOWN OF MAYVILLE WARDS 1-2',
 'CLARKTOWN OF RESEBURG WARD 1': 'CLARKTOWN OF RESEBURG WARDS 1-2',
 'CLARKTOWN OF RESEBURG WARD 2': 'CLARKTOWN OF RESEBURG WARDS 1-2',
 'CLARKTOWN OF SHERMAN WARD 1': 'CLARKTOWN OF SHERMAN WARDS 1-2',
 'CLARKTOWN OF SHERMAN WARD 2': 'CLARKTOWN OF SHERMAN WARDS 1-2',
 'CLARKTOWN OF WARNER WARD 1': 'CLARKTOWN OF WARNER WARDS 1-2',
 'CLARKTOWN OF WARNER WARD 2': 'CLARKTOWN OF WARNER WARDS 1-2',
 'CLARKTOWN OF WESTON WARD 1': 'CLARKTOWN OF WESTON WARDS 1-2',
 'CLARKTOWN OF WESTON WARD 2': 'CLARKTOWN OF WESTON WARDS 1-2',
 'CLARKTOWN OF YORK WARD 1': 'CLARKTOWN OF YORK WARDS 1-2',
 'CLARKTOWN OF YORK WARD 2': 'CLARKTOWN OF YORK WARDS 1-2',
 'COLUMBIACITY OF COLUMBUS WARD 1-8,10': 'COLUMBIACITY OF COLUMBUS WARD 10',
 'CRAWFORDTOWN OF CLAYTON WARD 1': 'CRAWFORDTOWN OF CLAYTON WARDS 1-3',
 'CRAWFORDTOWN OF CLAYTON WARD 2': 'CRAWFORDTOWN OF CLAYTON WARDS 1-3',
 'CRAWFORDTOWN OF CLAYTON WARD 3': 'CRAWFORDTOWN OF CLAYTON WARDS 1-3',
 'CRAWFORDTOWN OF EASTMAN WARD 1': 'CRAWFORDTOWN OF EASTMAN WARDS 1-2',
 'CRAWFORDTOWN OF EASTMAN WARD 2': 'CRAWFORDTOWN OF EASTMAN WARDS 1-2',
 'CRAWFORDTOWN OF PRAIRIE DU CHIEN WARD 1': 'CRAWFORDTOWN OF PRAIRIE DU CHIEN WARDS 1-2',
 'CRAWFORDTOWN OF PRAIRIE DU CHIEN WARD 2': 'CRAWFORDTOWN OF PRAIRIE DU CHIEN WARDS 1-2',
 'CRAWFORDTOWN OF WAUZEKA WARD 1': 'CRAWFORDTOWN OF WAUZEKA WARDS 1-2',
 'CRAWFORDTOWN OF WAUZEKA WARD 2': 'CRAWFORDTOWN OF WAUZEKA WARDS 1-2',
 'DANECITY OF FITCHBURG WARD 10-14': 'DANECITY OF FITCHBURG WARD 14',
 'DANECITY OF FITCHBURG WARD 5-9': 'DANECITY OF FITCHBURG WARDS 5-9',
 'DANECITY OF FITCHBURG WARDS 15-20': 'DANECITY OF FITCHBURG WARD 20',
 'DANECITY OF MIDDLETON WARDS 1-4,9,19-20': 'DANECITY OF MIDDLETON WARDS 1-4,9',
 'DANECITY OF STOUGHTON WARD 1-2': 'DANECITY OF STOUGHTON WARDS 1-2',
 'DANECITY OF STOUGHTON WARD 3-4,10-12': 'DANECITY OF STOUGHTON WARDS 3-4,12',
 'DANECITY OF STOUGHTON WARD 5-6': 'DANECITY OF STOUGHTON WARDS 5-6',
 'DANECITY OF SUN PRAIRIE WARD 1-5': 'DANECITY OF SUN PRAIRIE WARDS 1-5',
 'DANECITY OF SUN PRAIRIE WARD 10-14,20': 'DANECITY OF SUN PRAIRIE WARDS 10-14',
 'DANECITY OF SUN PRAIRIE WARD 15-19': 'DANECITY OF SUN PRAIRIE WARDS 15-19',
 'DANECITY OF SUN PRAIRIE WARD 6-9': 'DANECITY OF SUN PRAIRIE WARDS 6-9',
 'DANECITY OF VERONA WARD 1-5': 'DANECITY OF VERONA WARDS 1,5',
 'DANECITY OF VERONA WARD 6-9': 'DANECITY OF VERONA WARDS 6-9',
 'DANETOWN OF COTTAGE GROVE WARDS 1-7': 'DANETOWN OF COTTAGE GROVE WARDS 3,6',
 'DANETOWN OF DUNKIRK WARD 1-6': 'DANETOWN OF DUNKIRK WARD 1,3,5',
 'DANETOWN OF OREGON WARDS 1-4': 'DANETOWN OF OREGON WARD 1-4',
 'DANETOWN OF SPRINGFIELD WARDS 1-3': 'DANETOWN OF SPRINGFIELD WARD 1-3',
 'DANETOWN OF VIENNA WARD 1-2': 'DANETOWN OF VIENNA WARDS 1-2',
 'DANEVILLAGE OF DEFOREST WARDS 1-6,14-17': 'DANEVILLAGE OF DEFOREST WARD 1,3-6,15',
 'DODGECITY OF BEAVER DAM WARD 1,3,5': 'DODGECITY OF BEAVER DAM WARDS 1,3,5',
 'DODGECITY OF BEAVER DAM WARD 2,6': 'DODGECITY OF BEAVER DAM WARDS 2,6',
 'DODGECITY OF BEAVER DAM WARD 4,10': 'DODGECITY OF BEAVER DAM WARDS 4,10',
 'DODGECITY OF BEAVER DAM WARD 7,12-13': 'DODGECITY OF BEAVER DAM WARDS 7,12-13',
 'DODGECITY OF BEAVER DAM WARD 8,14': 'DODGECITY OF BEAVER DAM WARDS 8,14',
 'DODGECITY OF BEAVER DAM WARD 9,11': 'DODGECITY OF BEAVER DAM WARDS 9,11',
 'DODGECITY OF FOX LAKE WARD 1-3': 'DODGECITY OF FOX LAKE WARDS 1-3',
 'DODGECITY OF WAUPUN WARD 1-8': 'DODGECITY OF WAUPUN WARDS 1-8',
 'DODGETOWN OF ASHIPPUN WARD 1-4': 'DODGETOWN OF ASHIPPUN WARDS 1-4',
 'DODGETOWN OF BEAVER DAM WARD 1-4,7-11': 'DODGETOWN OF BEAVER DAM WARDS 1-4,7-11',
 'DODGETOWN OF BEAVER DAM WARD 5-6': 'DODGETOWN OF BEAVER DAM WARDS 5-6',
 'DODGETOWN OF BURNETT WARD 1-2': 'DODGETOWN OF BURNETT WARDS 1-2',
 'DODGETOWN OF CALAMUS WARD 1-2': 'DODGETOWN OF CALAMUS WARDS 1-2',
 'DODGETOWN OF CHESTER WARD 1-2': 'DODGETOWN OF CHESTER WARDS 1-2',
 'DODGETOWN OF EMMET WARD 1-2': 'DODGETOWN OF EMMET WARDS 1-2',
 'DODGETOWN OF FOX LAKE WARD 1-4': 'DODGETOWN OF FOX LAKE WARDS 1-4',
 'DODGETOWN OF HUBBARD WARD 1-4': 'DODGETOWN OF HUBBARD WARDS 1-4',
 'DODGETOWN OF HUBBARD WARD 5-6': 'DODGETOWN OF HUBBARD WARDS 5-6',
 'DODGETOWN OF HUSTISFORD WARD 1-2': 'DODGETOWN OF HUSTISFORD WARDS 1-2',
 'DODGETOWN OF LEBANON WARD 1-2': 'DODGETOWN OF LEBANON WARDS 1-2',
 'DODGETOWN OF LEROY WARD 1-2': 'DODGETOWN OF LEROY WARDS 1-2',
 'DODGETOWN OF OAK GROVE WARD 1-2': 'DODGETOWN OF OAK GROVE WARDS 1-2',
 'DODGETOWN OF OAK GROVE WARD 3-6': 'DODGETOWN OF OAK GROVE WARDS 3-6',
 'DODGETOWN OF PORTLAND WARD 1-2': 'DODGETOWN OF PORTLAND WARDS 1-2',
 'DODGETOWN OF RUBICON WARD 1-3': 'DODGETOWN OF RUBICON WARDS 1-3',
 'DODGETOWN OF THERESA WARD 1,3-7': 'DODGETOWN OF THERESA WARDS 1,3-7',
 'DODGETOWN OF TRENTON WARD 1-2': 'DODGETOWN OF TRENTON WARDS 1-2',
 'DODGETOWN OF WILLIAMSTOWN WARD 1-3': 'DODGETOWN OF WILLIAMSTOWN WARDS 1-3',
 'DODGEVILLAGE OF HUSTISFORD WARD 1-2': 'DODGEVILLAGE OF HUSTISFORD WARDS 1-2',
 'DODGEVILLAGE OF RANDOLPH WARD 1-2': 'DODGEVILLAGE OF RANDOLPH WARDS 1-2',
 'DODGEVILLAGE OF THERESA WARD 1-3': 'DODGEVILLAGE OF THERESA WARDS 1-3',
 'DOORCITY OF STURGEON BAY WARDS 1-2,29': 'DOORCITY OF STURGEON BAY WARDS 1-6,22-24,29',
 'DOORCITY OF STURGEON BAY WARDS 11-12': 'DOORCITY OF STURGEON BAY WARDS 11-17,28',
 'DOORCITY OF STURGEON BAY WARDS 13-14': 'DOORCITY OF STURGEON BAY WARDS 11-17,28',
 'DOORCITY OF STURGEON BAY WARDS 15-17,28': 'DOORCITY OF STURGEON BAY WARDS 11-17,28',
 'DOORCITY OF STURGEON BAY WARDS 18-19,25-26,30': 'DOORCITY OF STURGEON BAY WARDS 7-10,18-21,25-27,30',
 'DOORCITY OF STURGEON BAY WARDS 5-6,22-24': 'DOORCITY OF STURGEON BAY WARDS 1-6,22-24,29',
 'DOORCITY OF STURGEON BAY WARDS 7-8': 'DOORCITY OF STURGEON BAY WARDS 11-17,28',
 'DOORTOWN OF BAILEYS HARBOR WARD 1': 'DOORTOWN OF BAILEYS HARBOR WARDS 1-2',
 'DOORTOWN OF BAILEYS HARBOR WARD 2': 'DOORTOWN OF BAILEYS HARBOR WARDS 1-2',
 'DOORTOWN OF BRUSSELS WARD 1': 'DOORTOWN OF BRUSSELS WARDS 1-2',
 'DOORTOWN OF BRUSSELS WARD 2': 'DOORTOWN OF BRUSSELS WARDS 1-2',
 'DOORTOWN OF EGG HARBOR WARD 1': 'DOORTOWN OF EGG HARBOR WARDS 1-3',
 'DOORTOWN OF EGG HARBOR WARD 2': 'DOORTOWN OF EGG HARBOR WARDS 1-3',
 'DOORTOWN OF EGG HARBOR WARD 3': 'DOORTOWN OF EGG HARBOR WARDS 1-3',
 'DOORTOWN OF FORESTVILLE WARD 1': 'DOORTOWN OF FORESTVILLE WARDS 1-2',
 'DOORTOWN OF FORESTVILLE WARD 2': 'DOORTOWN OF FORESTVILLE WARDS 1-2',
 'DOORTOWN OF GARDNER WARD 1': 'DOORTOWN OF GARDNER WARDS 1-2',
 'DOORTOWN OF GARDNER WARD 2': 'DOORTOWN OF GARDNER WARDS 1-2',
 'DOORTOWN OF JACKSONPORT WARD 1': 'DOORTOWN OF JACKSONPORT WARDS 1-2',
 'DOORTOWN OF JACKSONPORT WARD 2': 'DOORTOWN OF JACKSONPORT WARDS 1-2',
 'DOORTOWN OF LIBERTY GROVE WARD 1': 'DOORTOWN OF LIBERTY GROVE WARDS 1-3',
 'DOORTOWN OF LIBERTY GROVE WARD 2': 'DOORTOWN OF LIBERTY GROVE WARDS 1-3',
 'DOORTOWN OF LIBERTY GROVE WARD 3': 'DOORTOWN OF LIBERTY GROVE WARDS 1-3',
 'DOORTOWN OF NASEWAUPEE WARD 1': 'DOORTOWN OF NASEWAUPEE WARDS 1-3',
 'DOORTOWN OF NASEWAUPEE WARD 2': 'DOORTOWN OF NASEWAUPEE WARDS 1-3',
 'DOORTOWN OF NASEWAUPEE WARD 3': 'DOORTOWN OF NASEWAUPEE WARDS 1-3',
 'DOORTOWN OF SEVASTOPOL WARD 2': 'DOORTOWN OF SEVASTOPOL WARDS 1-5',
 'DOORTOWN OF SEVASTOPOL WARDS 1,5': 'DOORTOWN OF SEVASTOPOL WARDS 1-5',
 'DOORTOWN OF SEVASTOPOL WARDS 3-4': 'DOORTOWN OF SEVASTOPOL WARDS 1-5',
 'DOORTOWN OF STURGEON BAY WARD 1': 'DOORTOWN OF STURGEON BAY WARDS 1-2',
 'DOORTOWN OF STURGEON BAY WARD 2': 'DOORTOWN OF STURGEON BAY WARDS 1-2',
 'DOUGLASCITY OF SUPERIOR WARD 1-3,7-8': 'DOUGLASCITY OF SUPERIOR WARDS 1-3,7-8',
 'DOUGLASCITY OF SUPERIOR WARD 13-16,20-22': 'DOUGLASCITY OF SUPERIOR WARDS 13-16,20-22',
 'DOUGLASCITY OF SUPERIOR WARD 17-19,30-32': 'DOUGLASCITY OF SUPERIOR WARDS 17-19,30-32',
 'DOUGLASCITY OF SUPERIOR WARD 23-29': 'DOUGLASCITY OF SUPERIOR WARDS 23-29',
 'DOUGLASCITY OF SUPERIOR WARD 4-6,9-12': 'DOUGLASCITY OF SUPERIOR WARDS 4-6,9-12',
 'DUNNCITY OF MENOMONIE WARD 1': 'DUNNCITY OF MENOMONIE WARDS 1-2',
 'DUNNCITY OF MENOMONIE WARD 10': 'DUNNCITY OF MENOMONIE WARDS 10-11',
 'DUNNCITY OF MENOMONIE WARD 11': 'DUNNCITY OF MENOMONIE WARDS 10-11',
 'DUNNCITY OF MENOMONIE WARD 2': 'DUNNCITY OF MENOMONIE WARDS 1-2',
 'DUNNCITY OF MENOMONIE WARD 3': 'DUNNCITY OF MENOMONIE WARDS 3-4',
 'DUNNCITY OF MENOMONIE WARD 4': 'DUNNCITY OF MENOMONIE WARDS 3-4',
 'DUNNCITY OF MENOMONIE WARD 5': 'DUNNCITY OF MENOMONIE WARDS 5,7',
 'DUNNCITY OF MENOMONIE WARD 7': 'DUNNCITY OF MENOMONIE WARDS 5,7',
 'DUNNCITY OF MENOMONIE WARD 8': 'DUNNCITY OF MENOMONIE WARDS 8-9',
 'DUNNCITY OF MENOMONIE WARD 9': 'DUNNCITY OF MENOMONIE WARDS 8-9',
 'DUNNTOWN OF DUNN WARD 1-2': 'DUNNTOWN OF DUNN WARDS 1-2',
 'EAU CLAIRECITY OF ALTOONA WARD 1': 'EAU CLAIRECITY OF ALTOONA WARDS 1-11',
 'EAU CLAIRECITY OF ALTOONA WARDS 2-3': 'EAU CLAIRECITY OF ALTOONA WARDS 12-15',
 'EAU CLAIRECITY OF ALTOONA WARDS 4-5': 'EAU CLAIRECITY OF ALTOONA WARDS 12-15',
 'EAU CLAIRECITY OF ALTOONA WARDS 6-11': 'EAU CLAIRECITY OF ALTOONA WARDS 1-11',
 'FORESTCITY OF CRANDON WARD 1': 'FORESTCITY OF CRANDON WARDS 1-4',
 'FORESTCITY OF CRANDON WARD 2': 'FORESTCITY OF CRANDON WARDS 1-4',
 'FORESTCITY OF CRANDON WARD 3': 'FORESTCITY OF CRANDON WARDS 1-4',
 'FORESTCITY OF CRANDON WARD 4': 'FORESTCITY OF CRANDON WARDS 1-4',
 'FORESTTOWN OF ARGONNE WARD 1': 'FORESTTOWN OF ARGONNE WARDS 1-3',
 'FORESTTOWN OF ARGONNE WARD 2': 'FORESTTOWN OF ARGONNE WARDS 1-3',
 'FORESTTOWN OF ARGONNE WARD 3': 'FORESTTOWN OF ARGONNE WARDS 1-3',
 'FORESTTOWN OF CRANDON WARD 1': 'FORESTTOWN OF CRANDON WARDS 1-3',
 'FORESTTOWN OF CRANDON WARD 2': 'FORESTTOWN OF CRANDON WARDS 1-3',
 'FORESTTOWN OF CRANDON WARD 3': 'FORESTTOWN OF CRANDON WARDS 1-3',
 'FORESTTOWN OF LAONA WARD 1': 'FORESTTOWN OF LAONA WARDS 1-3',
 'FORESTTOWN OF LAONA WARD 2': 'FORESTTOWN OF LAONA WARDS 1-3',
 'FORESTTOWN OF LAONA WARD 3': 'FORESTTOWN OF LAONA WARDS 1-3',
 'FORESTTOWN OF LINCOLN WARD 1': 'FORESTTOWN OF LINCOLN WARDS 1-3',
 'FORESTTOWN OF LINCOLN WARD 2': 'FORESTTOWN OF LINCOLN WARDS 1-3',
 'FORESTTOWN OF LINCOLN WARD 3': 'FORESTTOWN OF LINCOLN WARDS 1-3',
 'FORESTTOWN OF WABENO WARD 1': 'FORESTTOWN OF WABENO WARDS 1-5',
 'FORESTTOWN OF WABENO WARD 2': 'FORESTTOWN OF WABENO WARDS 1-5',
 'FORESTTOWN OF WABENO WARD 3': 'FORESTTOWN OF WABENO WARDS 1-5',
 'FORESTTOWN OF WABENO WARD 4': 'FORESTTOWN OF WABENO WARDS 1-5',

In [1016]:
# Checking any suspicious precinct, county
suspicious_precincts = pri_combined_df[
    pri_combined_df["precinct"].isna() |
    pri_combined_df["precinct"].str.strip().str.upper().str.contains(r"\w*TOTAL\w*", na=False) |
    pri_combined_df["precinct"].str.strip().str.upper().isin(["NONE", "NAN"]) |
    pri_combined_df["county"].isna() |
    pri_combined_df["county"].str.strip().str.upper().str.contains(r"\w*TOTAL\w*", na=False) |
    pri_combined_df["county"].str.strip().str.upper().isin(["NONE", "NAN"])
]

In [1017]:
# Select only the relevant columns
primary_data = pri_combined_df[["precinct", "party", "candidate", "votes"]]

primary_data

,precinct,party,candidate,votes
0,ADAMSTOWN OF ADAMS WARDS 1-3,REP,Marco Rubio,3
1,ADAMSTOWN OF ADAMS WARDS 1-3,REP,Ben Carson,0
2,ADAMSTOWN OF ADAMS WARDS 1-3,REP,Rand Paul,2
3,ADAMSTOWN OF ADAMS WARDS 1-3,REP,Mike Huckabee,1
4,ADAMSTOWN OF ADAMS WARDS 1-3,REP,Jim Gilmore,0
...,...,...,...,...
81475,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25",DEM,Martin O'Malley,3
81476,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25",DEM,Bernie Sanders,388
81477,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25",DEM,Uninstructed Delegation,1
81478,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25",DEM,Roque Rocky De La Fuente (Write-In),0
81479,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25",DEM,Scattering,0

In [1018]:
# Viewing candidate data
primary_data["candidate"].value_counts(dropna=False)

candidate
Scattering                             7760
Uninstructed Delegation                7760
Marco Rubio                            3880
Jeb Bush                               3880
Bernie Sanders                         3880
Martin O'Malley                        3880
Hillary Clinton                        3880
Victor Williams (Write-In)             3880
Ted Cruz                               3880
John R. Kasich                         3880
Ben Carson                             3880
Carly Fiorina                          3880
Rick Santorum                          3880
Donald J. Trump                        3880
Chris Christie                         3880
Jim Gilmore                            3880
Mike Huckabee                          3880
Rand Paul                              3880
Roque Rocky De La Fuente (Write-In)    3880
Name: count, dtype: int64

In [1019]:
# Cleaning Candidates

# Turning all primary data to uppercase
primary_data["candidate"] = primary_data["candidate"].astype(str).str.upper()

unwanted_keywords = [
    r"\w*VOTE\w*",
    r"\w*UNCOM\w*",
    r"\w*TOTAL\w*",
    r"\w*ATTERING\w*",
    r"\w*UNINSTRUCTED\w*",
    r"UNCOMMITTED", r"OTHER",r"Total Votes Cast",r"No Preference"
]

pattern = "|".join(unwanted_keywords)

# Assuming candidate column is already string and uppercase
primary_data = primary_data[~primary_data["candidate"].str.upper().str.contains(pattern, regex=True, na=False)]

#fIXING DE LA FUENTE
primary_data.loc[
    (
        primary_data["candidate"].str.contains("rocky.*fuente", case=False, na=False) |
        primary_data["candidate"].str.contains("LA FUENTE", case=False, na=False) |
        primary_data["candidate"].str.contains("\w*Fuque\w*", case=False, na=False)
    ),
    "candidate"
] = "LA FUENTE"

# # Fixing williams
primary_data.loc[
    primary_data["candidate"].str.contains("WILLIAMS", case=False, na=False),
    "candidate"
] = "WILLIAMS"

primary_data.loc[:, "candidate"] = primary_data["candidate"].replace({
    "Donald I. Trump": "Donald J. Trump",
})

# # Fixing the , candidate
# primary_data["candidate"] = (
#     primary_data["candidate"].str.split(",")
#     .str[0]
#     .str.strip()
#     )


# #Selecting only last name
primary_data["candidate"] = primary_data["candidate"].str.split().str[-1]

# # Fixing Christie
# primary_data.loc[
#     primary_data["candidate"].str.contains("CHRISTLE", case=False, na=False),
#     "candidate"
# ] = "CHRISTIE"

# # Fixing KASICH
# primary_data.loc[
#     primary_data["candidate"].str.contains("KAISCH", case=False, na=False),
#     "candidate"
# ] = "CHRISTIE"

# # Fixing O'MALLEY
# primary_data.loc[
#     primary_data["candidate"].str.contains("O'MALLEY", case=False, na=False),
#     "candidate"
# ] = "O'MAILEY"

# # Fixing O'MALLEY
# primary_data.loc[
#     primary_data["candidate"].str.contains("PATAKL", case=False, na=False),
#     "candidate"
# ] = "PATAKI"

# # Fixing O'MALLEY
# primary_data.loc[
#     primary_data["candidate"].str.contains("RUBLO", case=False, na=False),
#     "candidate"
# ] = "RUBIO"

# # Fixing Huckabee
# primary_data.loc[
#     primary_data["candidate"].str.contains("\w*ABEE\w*", case=False, na=False),
#     "candidate"
# ] = "HUCKABEE"

# # Fixing Fiorina
# primary_data.loc[
#     primary_data["candidate"].str.contains("\w*ORINA\W*", case=False, na=False),
#     "candidate"
# ] = "FIORINA"

# # Fixing Gray
# primary_data.loc[
#     primary_data["candidate"].str.contains("GREY", case=False, na=False),
#     "candidate"
# ] = "GRAY"

# # Fixing Wilson
# primary_data.loc[
#     primary_data["candidate"].str.contains("WISON", case=False, na=False),
#     "candidate"
# ] = "WILSON"


# # Fixing separator 
# primary_data["candidate"] = (
#     primary_data["candidate"]
#     .str.split(r"\s*(?:and|/|&|–|-|\+)\s*", n=1, expand=True)[0]
#     .str.strip()
#     .str.upper()
# )

# # Fixing McMullin

# primary_data.loc[
#     (
#         primary_data["candidate"].str.contains("MCMULLIN", case=False, na=False) |
#         primary_data["candidate"].str.contains("EVAN MCMULLEN", case=False, na=False)
#     ),
#     "candidate"
# ] = "MCMULLIN"

# primary_data.loc[
#     primary_data["candidate"].str.contains("De La Fuen", case=False, na=False),
#     "candidate"
# ] = "FUENTE D"

# primary_data.loc[:,"candidate"] = (
#     primary_data["candidate"].str.split().str[0].str.upper()
# )

primary_data["candidate"].value_counts(dropna=False)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_33704\1590360723.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  primary_data["candidate"] = primary_data["candidate"].astype(str).str.upper()
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_33704\1590360723.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  primary_data["candidate"] = primary_data["candidate"].str.split().str[-1]

candidate
RUBIO       3880
KASICH      3880
SANDERS     3880
O'MALLEY    3880
CLINTON     3880
WILLIAMS    3880
CRUZ        3880
BUSH        3880
FIORINA     3880
CARSON      3880
SANTORUM    3880
TRUMP       3880
CHRISTIE    3880
GILMORE     3880
HUCKABEE    3880
PAUL        3880
FUENTE      3880
Name: count, dtype: int64

In [1020]:
# Viewing Party
primary_data["party"].value_counts(dropna=False)

party
REP    50440
DEM    15520
Name: count, dtype: int64

In [1021]:
#=====================================
# This function is used to look up party
# for the candidate in the same df
#=====================================
def fill_party_from_data(row, df):
    if pd.notna(row["party"]):
        return row["party"]
    
    # Try to find other rows with the same candidate and known party
    matches = df[(df["candidate"] == row["candidate"]) & (df["party"].notna())]
    if not matches.empty:
        return matches["party"].iloc[0]  # Return the first match's party
    else:
        return None  # Still unknown

#=====================================
# Example usage (uncomment and modify for your workflow)
#=====================================
# Fill party using internal data
# primary_data["party"] = primary_data.apply(
#     lambda row: fill_party_from_data(row, primary_data),
#     axis=1
# )

primary_data["party"].value_counts(dropna=False)

party
REP    50440
DEM    15520
Name: count, dtype: int64

In [1022]:
# Cleaning Party
# Turning all general data party to uppercase
primary_data["party"] = primary_data["party"].astype(str).str.upper()

# primary_data["party"] = primary_data.apply(
#     lambda row: fill_party_from_data(row, primary_data),
#     axis=1
# )
primary_data["party"] = (
    primary_data["party"]
    .replace({
        "REPUBLICAN": "REP",
        "R": "REP",
        "DEMOCRATIC": "DEM",
        "DEMOCRAT":"DEM",
        "DEM": "DEM",
        "D": "DEM",
        "GREEN": "GRN",
        "G": "GREEN",
        "GREEN-RAINBOW":"GRN",
        "LIBERTARIAN": "LIB",
        "LBT": "LIB",
        "L": "LIB",
        "CONSTITUTION": "CON",
        "NP": "IND",
        "NON": "IND",
        "WRI": "IND",
        "WRITE-IN": "IND",
        "ONA": "IND",
        "GEN": "IND",
        "NONE":"UNK"
    })
)
primary_data["party"].value_counts(dropna=False)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_33704\453441538.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  primary_data["party"] = primary_data["party"].astype(str).str.upper()
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_33704\453441538.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  primary_data["party"] = (

party
REP    50440
DEM    15520
Name: count, dtype: int64

In [1023]:
primary_data.loc[:,"candidate_column"] = (
    "pri_" +
    primary_data["party"].str.lower() + "_" +
    primary_data["candidate"]
)

# pivot the table
primary_result = primary_data.pivot_table(
    index="precinct",
    columns="candidate_column",
    values="votes",
    aggfunc="sum",  
    fill_value=0
).reset_index()

primary_result

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_33704\2521670330.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  primary_data.loc[:,"candidate_column"] = (

candidate_column,precinct,pri_dem_CLINTON,pri_dem_FUENTE,pri_dem_O'MALLEY,pri_dem_SANDERS,pri_rep_BUSH,pri_rep_CARSON,pri_rep_CHRISTIE,pri_rep_CRUZ,pri_rep_FIORINA,pri_rep_GILMORE,pri_rep_HUCKABEE,pri_rep_KASICH,pri_rep_PAUL,pri_rep_RUBIO,pri_rep_SANTORUM,pri_rep_TRUMP,pri_rep_WILLIAMS
0,ADAMSCITY OF ADAMS WARD 1-4,130,0,1,123,3,1,0,83,0,0,2,16,2,4,0,140,0
1,"ADAMSCITY OF WISCONSIN DELLS WARDS 5,9",1,0,0,5,0,0,0,0,0,0,0,2,0,0,0,4,0
2,ADAMSTOWN OF ADAMS WARDS 1-3,79,0,3,81,0,0,0,86,0,0,1,14,2,3,1,164,0
3,ADAMSTOWN OF BIG FLATS WARD 1-2,56,0,0,89,0,2,0,66,0,0,2,6,0,3,0,117,0
4,ADAMSTOWN OF COLBURN WARD 1,6,0,0,17,0,1,0,13,0,0,1,4,0,0,0,37,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3574,WOODVILLAGE OF HEWITT WARD 1,56,0,0,86,0,2,0,114,0,0,2,22,0,2,0,87,0
3575,WOODVILLAGE OF MILLADORE WARD 1,14,0,0,22,0,0,0,31,0,0,0,0,0,1,0,27,0
3576,WOODVILLAGE OF PORT EDWARDS WARDS 1-3,136,0,0,167,2,6,0,175,0,0,0,51,0,2,0,166,0
3577,WOODVILLAGE OF RUDOLPH WARD 1,35,0,0,44,0,0,0,57,0,0,0,8,0,0,0,31,0
3578,WOODVILLAGE OF VESPER WARD 1,29,0,0,46,0,0,0,69,0,1,0,7,0,1,0,55,0

In [1024]:
# Process general files
general_df_list = []

for file in general_files:
    try:
        df = pd.read_csv(file)
        
        # Combine precinct as county + precinct
        df["precinct"] = df["county"].astype(str) + df["ward"].astype(str)
        df["precinct"] = df["precinct"].str.upper()
        df["county"] = df["county"].str.upper()

        # Cleaning maybe total precinct
        if 'precinct' in df.columns:
            df['precinct'] = df['precinct'].astype(str)                  
            df = df[df['precinct'].str.upper() != "TOTAL"]               
            df = df[df['precinct'].str.strip().str.upper() != "TOTAL"]   
            df = df[df['precinct'].str.upper() != "NAN"]                
        
        if 'county' in df.columns:
            df['county'] = df['county'].astype(str)                  
            df = df[df['county'].str.upper() != "TOTAL"]               
            df = df[df['county'].str.strip().str.upper() != "TOTAL"]   
            df = df[df['county'].str.upper() != "NAN"]       
            df = df[~df['county'].str.upper().str.contains(r"\w*TOTAL\w*", na=False)]      
            
        # Filtering out only President 
        if 'office' in df.columns:
            df = df[df["office"] == "President"]
        
        # Dropping duplicates value
        df = df.drop_duplicates()
        
        general_df_list.append(df)

    except Exception as e:
        print(f"Error in {file}: {e}")

# Combine all cleaned files
gen_combined_df = pd.concat(general_df_list, ignore_index=True)
# Checking any suspicious precinct
suspicious_precincts = gen_combined_df[
    gen_combined_df["precinct"].str.strip().str.upper().isin(["TOTAL", "NAN"])
]
gen_combined_df

,county,ward,office,district,total votes,party,candidate,votes,precinct
0,ADAMS,Town Of Adams Wards 1-3,President,NaN,618,REP,Donald J. Trump & Michael R. Pence,377,ADAMSTOWN OF ADAMS WARDS 1-3
1,ADAMS,Town Of Adams Wards 1-3,President,NaN,618,DEM,Hillary Clinton & Tim Kaine,207,ADAMSTOWN OF ADAMS WARDS 1-3
2,ADAMS,Town Of Adams Wards 1-3,President,NaN,618,CON,Darrell L. Castle & Scott N. Bradley,3,ADAMSTOWN OF ADAMS WARDS 1-3
3,ADAMS,Town Of Adams Wards 1-3,President,NaN,618,LIB,Gary Johnson & Bill Weld,22,ADAMSTOWN OF ADAMS WARDS 1-3
4,ADAMS,Town Of Adams Wards 1-3,President,NaN,618,WGR,Jill Stein & Ajamu Baraka,4,ADAMSTOWN OF ADAMS WARDS 1-3
...,...,...,...,...,...,...,...,...,...
61807,WOOD,"City Of Wisconsin Rapids Wards 16-23,25",President,NaN,2571,IND,Laurence Kotlikoff & Edward E. Leamer (Write-In),0,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25"
61808,WOOD,"City Of Wisconsin Rapids Wards 16-23,25",President,NaN,2571,IND,Tom Hoefling & Steve Schulin (Write-In),0,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25"
61809,WOOD,"City Of Wisconsin Rapids Wards 16-23,25",President,NaN,2571,IND,Joseph Maldonado (Write-In),0,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25"
61810,WOOD,"City Of Wisconsin Rapids Wards 16-23,25",President,NaN,2571,IND,Emidio Soltysik & Angela Nicole Walker (Write-In),0,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25"
61811,WOOD,"City Of Wisconsin Rapids Wards 16-23,25",President,NaN,2571,NaN,Scattering,0,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25"

In [1025]:
gen_combined_df.loc[(
    gen_combined_df["precinct"].str.contains("BARRONVILLAGE OF NEW AUBURN WARD 2", case=False, na=False) |
    gen_combined_df["precinct"].str.contains("BARRONVILLAGE OF NEW AUBURN WARD 3", case=False, na=False)
), "precinct"] = "BARRONVILLAGE OF NEW AUBURN WARDS 2-3"

In [1026]:
# Select only the relevant columns
general_data = gen_combined_df[["precinct", "party", "candidate", "votes"]]

general_data

,precinct,party,candidate,votes
0,ADAMSTOWN OF ADAMS WARDS 1-3,REP,Donald J. Trump & Michael R. Pence,377
1,ADAMSTOWN OF ADAMS WARDS 1-3,DEM,Hillary Clinton & Tim Kaine,207
2,ADAMSTOWN OF ADAMS WARDS 1-3,CON,Darrell L. Castle & Scott N. Bradley,3
3,ADAMSTOWN OF ADAMS WARDS 1-3,LIB,Gary Johnson & Bill Weld,22
4,ADAMSTOWN OF ADAMS WARDS 1-3,WGR,Jill Stein & Ajamu Baraka,4
...,...,...,...,...
61807,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25",IND,Laurence Kotlikoff & Edward E. Leamer (Write-In),0
61808,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25",IND,Tom Hoefling & Steve Schulin (Write-In),0
61809,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25",IND,Joseph Maldonado (Write-In),0
61810,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25",IND,Emidio Soltysik & Angela Nicole Walker (Write-In),0
61811,"WOODCITY OF WISCONSIN RAPIDS WARDS 16-23,25",NaN,Scattering,0

In [1027]:
# Viewing candidate data
general_data["candidate"] = general_data["candidate"].astype(str).str.upper()
general_data["candidate"].value_counts(dropna=False)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_33704\1743146100.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  general_data["candidate"] = general_data["candidate"].astype(str).str.upper()

candidate
DONALD J. TRUMP & MICHAEL R. PENCE                             3636
MICHAEL A. MATUREN & JUAN MUNOZ (WRITE-IN)                     3636
EMIDIO SOLTYSIK & ANGELA NICOLE WALKER (WRITE-IN)              3636
JOSEPH MALDONADO (WRITE-IN)                                    3636
TOM HOEFLING & STEVE SCHULIN (WRITE-IN)                        3636
LAURENCE KOTLIKOFF & EDWARD E. LEAMER (WRITE-IN)               3636
CHRIS KENISTON & DEACON TAYLOR (WRITE-IN)                      3636
MARSHALL SCHOENKE & JAMES CREIGHTON MITCHELL JR. (WRITE-IN)    3636
EVAN MCMULLIN & NATHAN JOHNSON (WRITE-IN)                      3636
HILLARY CLINTON & TIM KAINE                                    3636
CHERUNDA FOX & ROGER KUSHNER (WRITE-IN)                        3636
ROCKY ROQUE DE LA FUENTE & MICHAEL STEINBERG                   3636
MONICA MOOREHEAD & LAMONT LILLY                                3636
JILL STEIN & AJAMU BARAKA                                      3636
GARY JOHNSON & BILL WELD                                       3636
DARRELL L. CASTLE & SCOTT N. BRADLEY                           3636
SCATTERING                                                     3636
Name: count, dtype: int64

In [1028]:
# Cleaning Candidates

# Turning all general data to uppercase
general_data["candidate"] = general_data["candidate"].astype(str).str.upper()


unwanted_keywords = [
    r"\w*VOTE\w*",
    r"\w*UNCOM\w*",
    r"\w*TOTAL\w*",
    r"NAN",
    r"UNCERTIFIED",
    r"UNVERIFIED",
    r"NONE OF THE ABOVE",
    r"LBT",
    r"DEM",
    r"REP",
    r"GRN",
    r"NAN",
    r"\w*CANDIDATES\w*",
    "SCATTERING"
]

# Fixing FUENTE
general_data.loc[
    general_data["candidate"].str.contains("\w*FUENTE\w*", case=False, na=False),
    "candidate"
] = "FUENTE"
pattern = "|".join(unwanted_keywords)

# FILTER OUT TRASH WORDS
general_data = general_data[~general_data["candidate"].str.upper().str.contains(pattern, regex=True, na=False)]

# # Fixing Darrell Castle"
# general_data.loc[
#     general_data["candidate"].str.contains("\w*ASTLE\w*", case=False, na=False),
#     "candidate"
# ] = "CASTLE"

general_data.loc[
    general_data["candidate"].str.contains("\w*ATUREN\w*", case=False, na=False),
    "candidate"
] = "MATUREN"

general_data.loc[
    general_data["candidate"].str.contains("\w*OLTYSIK\w*", case=False, na=False),
    "candidate"
] = "SOLTYSIK"

general_data.loc[
    general_data["candidate"].str.contains("\w*MALDONADO\w*", case=False, na=False),
    "candidate"
] = "MALDONADO"

# # Fixing mixed president + vice_president by /
# general_data["candidate"] = (
#     general_data["candidate"].str.split("/")
#     .str[0]
#     .str.strip()
#     )

# #Selecting only last name
# general_data["candidate"] = general_data["candidate"].str.split().str[-1]

# Fixing the & candidate
general_data["candidate"] = (
    general_data["candidate"].str.split("&")
    .str[0]
    .str.strip()
    )




# # Fixing Cubbler
# general_data.loc[
#     ( 
#         general_data["candidate"].str.contains("\w*UBBIER\w*", case=False, na=False)|
#         general_data["candidate"].str.contains("\w*UBLER\w*", case=False, na=False)|
#         general_data["candidate"].str.contains("\w*OBBLER\w*", case=False, na=False),
#     "candidate")
# ] = "CUBBLER"


# Fixing Kotlikoff
general_data.loc[
    general_data["candidate"].str.contains("\w*LIKOFF\w*", case=False, na=False),
    "candidate"
] = "KOTLIKOFF"

# Fixing Valdivia
general_data.loc[
    general_data["candidate"].str.contains("\w*KENISTON\W*", case=False, na=False),
    "candidate"
] = "KENISTON"

# Fixing HOEFLING
general_data.loc[
    general_data["candidate"].str.contains("\w*HOEFFLING", case=False, na=False),
    "candidate"
] = "HOEFLING"

general_data.loc[
    general_data["candidate"].str.contains("\w*SCHOENKE", case=False, na=False),
    "candidate"
] = "SCHOENKE"


# Fixing McMullin
general_data.loc[
    general_data["candidate"].str.contains("MCMULLIN", case=False, na=False) ,
    "candidate"
] = "MCMULLIN"

general_data.loc[
    general_data["candidate"].str.contains("FOX", case=False, na=False) ,
    "candidate"
] = "FOX"

# Fixing LASTNAME + First name Initial
# general_data.loc[:,"candidate"] = (
#     general_data["candidate"].str.split().str[0].str.upper()
# )


# #Selecting only last name
general_data["candidate"] = general_data["candidate"].str.split().str[-1]

general_data["candidate"].value_counts(dropna=False)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_33704\248022595.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  general_data["candidate"] = general_data["candidate"].astype(str).str.upper()
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_33704\248022595.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  general_data["candidate"] = (
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_33704\248022595.py:127: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  general_data["candidate"] = general_data["candidate"].str.split().str[-1]

candidate
TRUMP        3636
CLINTON      3636
CASTLE       3636
JOHNSON      3636
STEIN        3636
MOOREHEAD    3636
FUENTE       3636
FOX          3636
MCMULLIN     3636
MATUREN      3636
SCHOENKE     3636
KENISTON     3636
KOTLIKOFF    3636
HOEFLING     3636
MALDONADO    3636
SOLTYSIK     3636
Name: count, dtype: int64

In [1029]:
# Viewing Party
general_data["party"].value_counts(dropna=False)

party
IND    39996
REP     3636
DEM     3636
CON     3636
LIB     3636
WGR     3636
Name: count, dtype: int64

In [1030]:
#=====================================
# This function is used to look up party
# for the candidate in the same df
#=====================================
def fill_party_from_data(row, df):
    if pd.notna(row["party"]):
        return row["party"]
    
    # Try to find other rows with the same candidate and known party
    matches = df[(df["candidate"] == row["candidate"]) & (df["party"].notna())]
    if not matches.empty:
        return matches["party"].iloc[0]  # Return the first match's party
    else:
        return None  # Still unknown
    

#=====================================
# Function to update the master candidate-party CSV
#=====================================
def update_master_candidate_party(df, master_path):
    # Read the existing master file
    master_df = pd.read_csv(master_path)

    # Filter and combine only known party entries (exclude 'UNK')
    new_data = (
        df[["candidate", "party"]]
        .dropna()
        .query('party != "UNK"')
        .drop_duplicates()
    )

    # Merge with master and remove duplicates by candidate
    updated_master = pd.concat([master_df, new_data]).drop_duplicates(subset="candidate")

    # Save updated version
    updated_master.to_csv(master_path, index=False)


#=====================================
# Function to update the master candidate-party CSV
#=====================================
def update_master_candidate_party(df, master_path):
    # Read the existing master file
    master_df = pd.read_csv(master_path)

    # Filter and combine only known party entries (exclude 'UNK')
    new_data = (
        df[["candidate", "party"]]
        .dropna()
        .query('party != "UNK"')
        .drop_duplicates()
    )

    # Merge with master and remove duplicates by candidate
    updated_master = pd.concat([master_df, new_data]).drop_duplicates(subset="candidate")

    # Save updated version
    updated_master.to_csv(master_path, index=False)


#=====================================
# Example usage (uncomment and modify for your workflow)
#=====================================
# Fill party using internal data
# general_data["party"] = general_data.apply(
#     lambda row: fill_party_from_data(row, general_data),
#     axis=1
# )

# # Fill remaining party using general master CSV
# master_party_df = pd.read_csv(r"C:\Huy Phan\College\VoterTurnout\data\cleaned_data\gen_can_party.csv") # USE YOUR OWN ADDRESS
# general_data = fill_party_from_master(general_data, master_party_df)
general_data["party"].value_counts(dropna=False)

party
IND    39996
REP     3636
DEM     3636
CON     3636
LIB     3636
WGR     3636
Name: count, dtype: int64

In [1031]:
# Cleaning Party
# Turning all general data party to uppercase
general_data["party"] = general_data["party"].astype(str).str.upper()

general_data["party"] = (
    general_data["party"]
    .replace({
        "REPUBLICAN": "REP",
        "R": "REP",
        "DEMOCRATIC": "DEM",
        "DEMOCRAT":"DEM",
        "DEM": "DEM",
        "D": "DEM",
        "GREEN": "GRN",
        "G": "GRN",
        "WGR":"GRN",
        "GREEN AND RAINBOW":"GRN",
        "GREEN-RAINBOW":"GRN",
        "LIBERTARIAN": "LIB",
        "LIBERTARIN":"LIB",
        "LPN":"LIB",
        "LBT": "LIB",
        "L": "LIB",
        "IAP":"CON",
        "CONSTITUTION": "CON",
        "AMERICAN DELTA":"AMD",
        "PROHIBITION":"PRO",
        "NP": "IND",
        "NON": "IND",
        "WRI": "IND",
        "WRITE-IN": "IND",
        "ONA": "IND",
        "GEN": "IND",
        "NONE":"UNK",
        "NPA":"IND",
        "UST":"CON",
        "NPP":"IND",
        "(WRITE-IN)":"IND"
    })
)

general_data["party"].value_counts(dropna=False)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_33704\4120040037.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  general_data["party"] = general_data["party"].astype(str).str.upper()
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_33704\4120040037.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  general_data["party"] = (

party
IND    39996
REP     3636
DEM     3636
CON     3636
LIB     3636
GRN     3636
Name: count, dtype: int64

In [1032]:
# UPDATE MASTER FILE, CAREFUL
update_master_candidate_party(general_data, r"C:\Huy Phan\College\VoterTurnout\data\cleaned_data\gen_can_party.csv")

In [1033]:
general_data["candidate_column"] = (
    "gen_" +
    general_data["party"].str.lower() + "_" +
    general_data["candidate"].str.split().str[-1].str.upper()
)

# pivot the table
general_result = general_data.pivot_table(
    index="precinct",
    columns="candidate_column",
    values="votes",
    aggfunc="sum",  
    fill_value=0
).reset_index()

general_result

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_33704\1829951435.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  general_data["candidate_column"] = (

candidate_column,precinct,gen_con_CASTLE,gen_dem_CLINTON,gen_grn_STEIN,gen_ind_FOX,gen_ind_FUENTE,gen_ind_HOEFLING,gen_ind_KENISTON,gen_ind_KOTLIKOFF,gen_ind_MALDONADO,gen_ind_MATUREN,gen_ind_MCMULLIN,gen_ind_MOOREHEAD,gen_ind_SCHOENKE,gen_ind_SOLTYSIK,gen_lib_JOHNSON,gen_rep_TRUMP
0,ADAMSCITY OF ADAMS WARD 1-4,6,329,6,0,1,0,0,0,0,0,4,2,0,0,16,379
1,"ADAMSCITY OF WISCONSIN DELLS WARDS 5,9",0,7,0,0,0,0,0,0,0,0,0,0,0,0,1,14
2,ADAMSTOWN OF ADAMS WARDS 1-3,3,207,4,0,0,0,0,0,0,0,3,1,0,0,22,377
3,ADAMSTOWN OF BIG FLATS WARD 1-2,4,169,4,0,0,0,0,0,0,0,0,0,0,0,10,300
4,ADAMSTOWN OF COLBURN WARD 1,0,42,2,0,0,0,0,0,0,0,0,0,0,0,1,85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3630,WOODVILLAGE OF HEWITT WARD 1,1,181,3,0,0,0,0,0,0,0,1,1,0,0,16,275
3631,WOODVILLAGE OF MILLADORE WARD 1,2,47,3,0,0,0,0,0,0,0,0,0,0,0,5,79
3632,WOODVILLAGE OF PORT EDWARDS WARDS 1-3,7,389,9,0,1,0,0,0,0,0,4,0,0,0,40,515
3633,WOODVILLAGE OF RUDOLPH WARD 1,2,101,2,0,1,0,0,0,0,0,0,0,0,0,5,140
3634,WOODVILLAGE OF VESPER WARD 1,2,89,2,0,0,0,0,0,0,0,0,0,0,0,15,188

In [1034]:
# Merge
combined = pd.merge(primary_result, general_result, on="precinct", how="inner")

# Convert DEM primary columns to numeric and calculate total
dem_cols = combined.filter(like="pri_dem_").columns
combined[dem_cols] = combined[dem_cols].apply(pd.to_numeric, errors="coerce")
combined["dem_primary_total"] = combined[dem_cols].sum(axis=1)

rep_cols = combined.filter(like="pri_rep_").columns
combined[rep_cols] = combined[rep_cols].apply(pd.to_numeric, errors="coerce")
combined["rep_primary_total"] = combined[rep_cols].sum(axis=1)

# Convert general election columns to numeric and calculate total

gdem_cols = combined.filter(like="gen_dem_").columns
combined[gdem_cols] = combined[gdem_cols].apply(pd.to_numeric, errors="coerce")
combined["dem_general_total"] = combined[gdem_cols].sum(axis=1)

grep_cols = combined.filter(like="gen_rep_").columns
combined[grep_cols] = combined[grep_cols].apply(pd.to_numeric, errors="coerce")
combined["rep_general_total"] = combined[grep_cols].sum(axis=1)

# Convert all numeric columns to int
for col in combined.columns[1:]:
    combined[col] = pd.to_numeric(combined[col], errors='coerce').fillna(0).astype(int)

# Identify filtered-out precincts
primary_precincts = set(primary_result["precinct"])
general_precincts = set(general_result["precinct"])
combined_precincts = set(combined["precinct"])

primary_filtered_out = primary_precincts - combined_precincts
general_filtered_out = general_precincts - combined_precincts


combined

candidate_column,precinct,pri_dem_CLINTON,pri_dem_FUENTE,pri_dem_O'MALLEY,pri_dem_SANDERS,pri_rep_BUSH,pri_rep_CARSON,pri_rep_CHRISTIE,pri_rep_CRUZ,pri_rep_FIORINA,...,gen_ind_MCMULLIN,gen_ind_MOOREHEAD,gen_ind_SCHOENKE,gen_ind_SOLTYSIK,gen_lib_JOHNSON,gen_rep_TRUMP,dem_primary_total,rep_primary_total,dem_general_total,rep_general_total
0,ADAMSCITY OF ADAMS WARD 1-4,130,0,1,123,3,1,0,83,0,...,4,2,0,0,16,379,254,251,329,379
1,"ADAMSCITY OF WISCONSIN DELLS WARDS 5,9",1,0,0,5,0,0,0,0,0,...,0,0,0,0,1,14,6,6,7,14
2,ADAMSTOWN OF ADAMS WARDS 1-3,79,0,3,81,0,0,0,86,0,...,3,1,0,0,22,377,163,271,207,377
3,ADAMSTOWN OF BIG FLATS WARD 1-2,56,0,0,89,0,2,0,66,0,...,0,0,0,0,10,300,145,196,169,300
4,ADAMSTOWN OF COLBURN WARD 1,6,0,0,17,0,1,0,13,0,...,0,0,0,0,1,85,23,56,42,85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3477,WOODVILLAGE OF HEWITT WARD 1,56,0,0,86,0,2,0,114,0,...,1,1,0,0,16,275,142,229,181,275
3478,WOODVILLAGE OF MILLADORE WARD 1,14,0,0,22,0,0,0,31,0,...,0,0,0,0,5,79,36,59,47,79
3479,WOODVILLAGE OF PORT EDWARDS WARDS 1-3,136,0,0,167,2,6,0,175,0,...,4,0,0,0,40,515,303,402,389,515
3480,WOODVILLAGE OF RUDOLPH WARD 1,35,0,0,44,0,0,0,57,0,...,0,0,0,0,5,140,79,96,101,140
3481,WOODVILLAGE OF VESPER WARD 1,29,0,0,46,0,0,0,69,0,...,0,0,0,0,15,188,75,133,89,188

In [1035]:


combined.to_csv("WI.csv", index=False)
# Step 3: Identify unmatched precincts and retrieve full rows
combined_precincts = set(combined["precinct"])

# Rows in primary_result but not in combined
primary_filtered_out = primary_result[~primary_result["precinct"].isin(combined_precincts)]
primary_filtered_out.to_csv("WI_primary_filtered.csv", index=False)

# Rows in general_result but not in combined
general_filtered_out = general_result[~general_result["precinct"].isin(combined_precincts)]
general_filtered_out.to_csv("WI_general_filtered.csv", index=False)

In [1036]:
print(f"primary: {len(primary_precincts)}, general: {len(general_precincts)}, combined: {len(combined)}")

primary: 3579, general: 3635, combined: 3482

In [1037]:
print(f"primary: {len(pri_combined_df['county'].unique())}, general: {len(gen_combined_df['county'].unique())}")

primary: 72, general: 72

In [1038]:
pri_combined_df['jurisdiction'].unique()

KeyError: 'jurisdiction'

In [ ]:
gen_combined_df['county'].unique()

array(['CARSON CITY', 'CHURCHILL', 'CLARK', 'DOUGLAS', 'ELKO',
       'ESMERALDA', 'EUREKA', 'HUMBOLDT', 'LANDER', 'LINCOLN', 'LYON',
       'MINERAL', 'NYE', 'PERSHING', 'STOREY', 'WASHOE', 'WHITE PINE'],
      dtype=object)

In [ ]:
primary_counties = set(pri_combined_df['jurisdiction'].dropna().str.strip().str.upper())
general_counties = set(gen_combined_df['county'].dropna().str.strip().str.upper())

diff = primary_counties - general_counties
print(f"Counties in primary but not in general: {len(diff)}")
print(diff)

Counties in primary but not in general: 1
{'YE'}